### ISSUE TITLE
Doesn't work properly with non-zero scroll-margin

### ISSUE THREAD

**Issue by skissue** [KeyWeeUsr/typewriter-roll-mode#1]
Hi, thanks for the cool package 🙂.

I seem to have found a small bug. When `scroll-margin` is non-zero, then that number of lines will always be shown above the active line. When `typewriter-roll-keep-in-focus` is also non-zero, it seems that the greater value is the one that takes effect.

I was able to work around this by dynamically binding `scroll-margin` to 0 in `typewriter-roll--scroll-up` like so:

``` emacs-lisp
(defsubst typewriter-roll--scroll-up ()
  "Scroll current line to the top."
  (let ((scroll-margin 0))
    (recenter-top-bottom typewriter-roll-keep-in-focus)))
```

This approach also seems to work:

``` emacs-lisp
(defsubst typewriter-roll--scroll-up ()
  "Scroll current line to the top."
  (let ((scroll-margin typewriter-roll-keep-in-focus))
    (recenter-top-bottom 0)))
```

**Comment by KeyWeeUsr** [comment]
@skissue Hi and sorry for such a delayed response! :innocent: 

I've verified the behavior and added a customize variable for it in [`1.2.0`](https://github.com/KeyWeeUsr/typewriter-roll-mode/releases/tag/1.2.0). Now you can decide whether to prefer `scroll-margin` or `keep-in-focus`. There are also some new tests, so both the default behavior and the customized one are checked.
